### ISSUE TITLE
Expose additional metadata fields in the search UI

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#157]
As of March 23, the ROR API has the full GRID metadata set for active records. No changes have yet been made to the front-end search UI. We need to determine if any of the new metadata fields should be exposed in the UI in the future. This determination will be informed by a balance of community feedback, documented use cases/benefits, and implementation constraints (e.g., design implications, resourcing to take on the restructuring, prioritization with regard to other development work, etc.)

See the metadata fields in the JSON structure documented here: https://github.com/ror-community/ror-api

Example record UI:
![Screen Shot 2021-03-24 at 1 31 54 PM](https://user-images.githubusercontent.com/45110557/112379375-4fb9c800-8ca5-11eb-8295-635ffeb97485.png)

Specific questions for consideration: 
- If the record exposes relationships, should it show all relationships or just some of them? 
- If the record includes location data (currently, only country is exposed), which data would be most useful to expose?
- Are there other fields that should be exposed?

**Comment by icraig-afk** [comment]
My preferences would be to include city, state, country as address fields. The type (education, company etc), I'd retain, alongside the URL. I would value the addition of an active/inactive flag, but that only becomes useful post a clean-up of what is active/inactive . For relationships I would have a binary yes/no on whether it has relationships - most records do not - and then for those that do I'd recommend a link to enable drill down/up within a hierarchical tree. Something to consider would be a timestamp of last update/review. I'd also enable feedback to be initiated from within the web UI itself, rather than a separate form that forces the user to copy/paste info that could be pre-populated. Finally, not strictly for the UI, but feeds into the date of last review and active/inactive fields, some form of automated URL checker to check for broken links, redirects etc. These are very strong signals that something has changed on the record

**Comment by BMissell** [comment]
I'd also like to see the relationships in a pop-up window (or link to another page), with an expandable hierarchical tree.  The Smithsonian, for instance, has too many relationships to be displayed in the record ( https://ror.org/01pp8nd67 ).  It would be nice if the hierarchy includes the full ROR ID of the parent/child/related entity, so you can click on it and go.  The yes/no binary in the UI on whether it has relationships, that links to the hierarchical tree, would be easily understood and not clutter the record.  City, State, Country would be helpful in the UI.

**Comment by amandafrench** [comment]
Thanks for the input, @BMissell -- this whole issue is currently under review (as of February), so your suggestions will be considered, for sure. Country is already in the UI, to clarify (it's the little colored tag at bottom left), but City and State might be good additions. 

You can see the whole product development board at https://github.com/orgs/ror-community/projects/10 if you're curious about what's next up.

**Comment by JE212** [comment]
Echoing what has already been said here - especially around full address information, org type and last review/change date. Keeping the heirachies visible on the record page would be most useful from my perspective, (even though some will have many) rather than an extra link to follow. The binary flag for relationships is a great idea - could you return this in search results? It would also be good to have this in data dump files, too, for clarity. 

Thanks for all your work!

**Comment by amandafrench** [comment]
@JE212 Thanks for your comments!
