### ISSUE TITLE
Issues with case sensitivity in API filters

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#175]
API filters appear to have case sensitivity, e.g.:

`https://api.ror.org/organizations?filter=types:Education` returns 19639 results
`https://api.ror.org/organizations?filter=types:education` returns 0 results

`https://api.ror.org/organizations?filter=country.country_name:Colombia` returns 319 results
`https://api.ror.org/organizations?filter=country.country_name:colombia` returns 0 results

Case sensitivity does not appear to impact general API queries (e.g., https://api.ror.org/organizations?query=colombia vs. https://api.ror.org/organizations?query=Colombia) or the search UI (colombia vs. Colombia). 

Is this intended functionality? If so, API documentation should be clarified so users set up queries appropriately. If not intended, can we make the filters case-insensitive?

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-api/pull/242
https://github.com/ror-community/ror-api/pull/243

- `types` filter values converted to sentence case
- `country.country_code` filter values converted to upper case
- `country.country_name` filter values converted to sentence case

Also, `country.country_name` now allows up to 1 comma character in the filter value, as there is one Geonames country name that contains a comma: `Bonaire, Saint Eustatius and Saba`. For now, the allowed number of commas per country_name filter value is hard-coded at 1. This will have to be adjusted if there's ever a case where a country name has multiple commas.

Expected behavior:
- Multiple instances of the same filter should be allowed (including multiple instances of `country.country_name` values with 1 comma). These don't acutally produce results, but shouldn't throw an error.
- Filters with empty values should be allowed. Again, they don't do anything, but shouldn't throw an error
- Unsupported filters (anything other than `type`, `country.country_code`, or `country.country_name` should throw an error
-
