### ISSUE TITLE
Error 500 when trying to access a GRID entity

### ISSUE THREAD

**Issue by briatte** [ror-community/ror-api#188]
The following requests currently sends back an Error 500:

https://api.ror.org/organizations?query=%22grid.449627.a%22

I cannot find anything that might justify that in the corresponding entry:

https://grid.ac/institutes/grid.449627.a

Found by @toumi-ais

**Comment by lizkrznarich** [comment]
@briatte Thanks for raising this. This is due to our use of [pycountry](https://pypi.org/project/pycountry/) in the query API, which does not support unofficial ISO-3166 country codes which _are_ supported in Geonames. As a result, queries that return results with XK, the provisional ISO code for Kosovo, return a 500 error. I have queried all GRID IDs in the ROR API and have only found this issue with the 17 records containing XK (grid.412416.4, grid.448866.0, grid.449627.a, grid.483264.f, grid.483487.4, grid.491739.1, grid.493533.b, grid.500953.a, grid.501376.6, grid.501581.8, grid.501658.f, grid.501930.e, grid.501948.1, grid.502107.1, grid.502305.1, grid.502313.6, grid.502329.f). We are looking into solutions for this, such as alternative country code packages that support all codes used in Geonames. In the meantime, note that this issue only affects querying, and it is possible to retrieve ROR records with country code XK, ex ```curl https://api.ror.org/organizations/05t3p2g92```.

**Comment by mariagould** [comment]
This will be addressed via #195

**Comment by lizkrznarich** [comment]
Hi @briatte as of May, this has been fixed and your query example now succeeds.
