### ISSUE TITLE
https://api.ror.org/organizations API maximum 500 pages

### ISSUE THREAD

**Issue by oroques72** [ror-community/ror-api#205]
As explained in the documentation, a page returns 20 organizations and since there are 102392 organizations (the number of organieations is provided by the meta parameter number_of_results":102392 in the JSON output) I will expect about 5120 pages

but a call up to 500 FAILS !

Exemple :
curl https://api.ror.org/organizations?page=2000
{"errors":["page '2000' outside of range 1-500"]}

Sow it seems impossible using the REST API https://api.ror.org/organizations to retrieve all organizations.
Regards

**Comment by lizkrznarich** [comment]
Hi @oroques72 , the 10,000 record limit is an inherent limitation in Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html . We are currently considering implementing cursor-based pagination in order to overcome this challenge on https://github.com/ror-community/ror-api/issues/50. 

If you need to retrieve all ROR records, however, the data dump file is a much more efficient approach https://ror.readme.io/docs/data-dump . ROR data only changes in the API when it is also changed in the data dump, therefore the data in the API is always the same as in the data dump file. The API is best for use cases that involve querying or retrieving individual records by ID.
