### ISSUE TITLE
Users need to be able to download the entire ROR dataset

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#26]

**Comment by mariagould** [comment]
@mfenner we discussed this today. Dominika and Geoff want to take a look at the data first before we make it public. We are planning to move forward with hosting it on Figshare.

**Comment by mariagould** [comment]
@mfenner I've set up an account in Figshare: https://figshare.com/authors/ROR_Community/6832769. I can share the login info with you. 

Can we discuss what needs to happen next? I think it would be good to have a csv and I'm wondering what else needs to be done to get there.

**Comment by lucboruta** [comment]
The JSON schema used in https://github.com/ror-community/ror-api/tree/master/rorapi/data is not strictly identical to the schema used by GRID. The (only?) difference is that GRID provides a JSON object with two fields `version` and `institutes`, whereas ROR currently provides the JSON array of institutes with no envelope.

Is there any chance you could adopt the same format for the public data dumps, at least for the top-level fields and fields that are shared by both GRID and ROR, so that projects that build upon GRID could also build upon ROR without tweaking their code?

**Comment by mfenner** [comment]
That is a good suggestion, we will look into it.

**Comment by mariagould** [comment]
Closing this issue because the data download has been made available. Moved comment to #58
