### ISSUE TITLE
Unable to load data dump

### ISSUE THREAD

**Issue by noppasha1** [ror-community/ror-api#408]
Hi
 
I am trying to start ROR-api in a Docker, and faced several issues. Some of them (modules conflics) were possible to be solved myself.
Anyway, I came to: "ERROR: ROR dataset for file v1.56-2024-11-19 not found. Please generate the data dump first."
when calling "docker-compose exec web python manage.py setup v1.56-2024-11-19 -s 2" as said in the instruction
Can anyone show me my mistake?

**Comment by noppasha1** [comment]
I also tried "-s 1" option and other filenames from ror-data repo

**Comment by lizkrznarich** [comment]
@noppasha1 Please comment out this line https://github.com/ror-community/ror-api/blob/8a5a5ae8b483564c966a7184349c581dcae756ef/rorapi/management/commands/setup.py#L13 to run the  command without the Github personal access token var. The ror-data repository is public, however, internally, we send an access token when retrieving the data dump in order to avoid being rate-limited when we need to run this request multiple times. External users do not have access to this token but can still run the command without the token by commenting out that line.

**Comment by noppasha1** [comment]
Thanks, worked fine!

In case you are modifing instruction or repo, i've also faced the need to install python-magic, jsonschema and iso639-lang during docker-compose

Should API be accesable from localhost:9200 right now, or do i need some other opertions to do?

**Comment by lizkrznarich** [comment]
@noppasha1 Great! I have updated the dev instructions with that note here https://github.com/ror-community/ror-api?tab=readme-ov-file#pre-requisites . Per the readme, the API is available at http://localhost:9292/organizations . Elasticsearch runs on 9200 and can be queried directly using Elasticsearch syntax, but the API is on 9292.

The libraries you mentioned are included in the requirements.txt, so should be installed automatically after running docker-compose up . These are new since approximately March 2024, so if you had run docker-compose up before then and not destroyed the containers, you would need to run docker-compose up --build in order to trigger install of the newer libraries.
