### ISSUE TITLE
Confirm approach for format of ROR JSON

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#58]
_Originally posted by @lucboruta in https://github.com/ror-community/ror-api/issues/26#issuecomment-506358622_

> The JSON schema used in https://github.com/ror-community/ror-api/tree/master/rorapi/data is not strictly identical to the schema used by GRID. The (only?) difference is that GRID provides a JSON object with two fields `version` and `institutes`, whereas ROR currently provides the JSON array of institutes with no envelope. Is there any chance you could adopt the same format for the public data dumps, at least for the top-level fields and fields that are shared by both GRID and ROR, so that projects that build upon GRID could also build upon ROR without tweaking their code?

Per discussion w/implementation team: This is not just about the data dump but about the overall approach to the format. Should the data dump match GRID or match the ROR API?

**Comment by martijnvanbeers** [comment]
I was going to suggest the deviating from grid further rather than less. Instead of having a json file containing an array of records, I think it's better to have the file in jsonlines format, which is one json object per line (see https://jsonlines.org for details).

This lets you start processing the data as soon as you've read in a single line, rather than first having to parse the entire file as json, and would even allow for parallel processing.

As for having the version metadata in the file, that could still work. You'd just define the convention that the first line is the metadata record. But I think getting that information from the filename is sufficient

**Comment by mariagould** [comment]
Thank you @martijnvanbeers this is really helpful feedback.

**Comment by lizkrznarich** [comment]
@lucboruta @martijnvanbeers GRID has sunset its public offering as of Sept 2021, and ROR's data model has since begun to diverge. It will diverge even further later in 2023 with the planned v2.0 schema, which is currently open for public comment  https://docs.google.com/document/d/1JNDMoKmjR2y0quWXwFfoJTsIttbltJVN0l5Wddw1cIk . Given this case, aligning the ROR data model with GRID is no longer under consideration, so I'm closing this issue. We welcome your feedback on schema 2.0, though!
