### ISSUE TITLE
Create obsolete json tombstone page

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-api#99]

**Comment by paulmillar** [comment]
Hi @eshadatta-crossref,

It would be helpful if this issue had some more details.  What is a tombstone page?  What information should it contain?  Where will that information be visible?

**Comment by eshadatta-crossref** [comment]
Hi @paulmillar ,

Thanks for your question. This will be in place for records that might become obsolete. It is still in our backlog as we work on creating curator workflows. The timeline for this particular work has not yet been determined. Thanks!

**Comment by lizkrznarich** [comment]
@paulmillar To add to @eshadatta-crossref 's response, the tombstone page concept borrows from the same concept in DOI best practice, ex https://support.datacite.org/docs/tombstone-pages. Since ROR IDs are intended to be persistent, if an ID is no longer available for whatever reason, we'll leave some record (in both the API and UI) indicating that there was previously an ID here and now there's not. This was not a practice in GRID, so also not a practice in ROR releases that inherited records from GRID (as you've found). It remains to be determined if we'll go back and diff all the previous releases to find where tombstones might beed to be added (but it may be a good idea, since, as you've noted, there are IDs out in the world that no longer resolve to records).

**Comment by paulmillar** [comment]
Thanks @eshadatta-crossref and @lizkrznarich for your replies.

This is very good.  I was hoping you were adopting something similar to DataCite's Tombstone concept.

I found some cases where ROR identifiers have "mysteriously" disappeared, which I've documented in issue #199.  These resulted in "dangling links" in other data bases (wikidata, to be specific).

Having tombstone pages/records would certainly help in these circumstances.
